// <auto-generated />
using System;
using ApotekConsoleApp.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApotekConsoleApp.Migrations
{
    [DbContext(typeof(ApotekDbContext))]
    partial class ApotekDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApotekConsoleApp.Models.Obat", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("Harga");

                    b.Property<string>("Kode");

                    b.Property<string>("Nama");

                    b.Property<int>("Stok");

                    b.HasKey("Id");

                    b.ToTable("Obats");
                });

            modelBuilder.Entity("ApotekConsoleApp.Models.Transaksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Kode");

                    b.Property<int>("Total");

                    b.HasKey("Id");

                    b.ToTable("Transaksis");
                });

            modelBuilder.Entity("ApotekConsoleApp.Models.TransaksiDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Jumlah");

                    b.Property<int?>("ObatId");

                    b.Property<int?>("TransaksiId");

                    b.HasKey("Id");

                    b.HasIndex("ObatId");

                    b.HasIndex("TransaksiId");

                    b.ToTable("TransaksiDetails");
                });

            modelBuilder.Entity("ApotekConsoleApp.Models.TransaksiDetail", b =>
                {
                    b.HasOne("ApotekConsoleApp.Models.Obat", "Obat")
                        .WithMany()
                        .HasForeignKey("ObatId");

                    b.HasOne("ApotekConsoleApp.Models.Transaksi", "Transaksi")
                        .WithMany("TransaksiDetails")
                        .HasForeignKey("TransaksiId");
                });
#pragma warning restore 612, 618
        }
    }
}
